name: Update Game Hashes

on:
  workflow_dispatch:

jobs:
  update-game-hashes:
    runs-on: self-hosted
    env:
        STEAM_USER: ${{ secrets.STEAM_USER }}
        STEAM_PASS: ${{ secrets.STEAM_PASS }}
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Clone the NexusMods.App repo
      - name: Clone NexusMods.App & Make Folders
        run: |
          mkdir output
          git clone https://github.com/Nexus-Mods/NexusMods.App
          cd NexusMods.App
          git submodule update --init --recursive

      - name: Build
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet build -c Release
          
      - name: Index Stardew Valley (Steam)
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet run --no-restore --no-build -c Release --property WarningLevel=0 -- as-main steam app index -o $GITHUB_WORKSPACE/json -a 413150 

      - name: Index Cyberpunk (Steam)
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet run --no-restore --no-build -c Release --property WarningLevel=0 -- as-main steam app index -o $GITHUB_WORKSPACE/json -a 1091500

      - name: Index Cyberpunk - Phantom Liberty (Steam)
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet run --no-restore --no-build -c Release --property WarningLevel=0 -- as-main steam app index -o $GITHUB_WORKSPACE/json -a 2138330

      - name: Index Baldurs Gate 3 (Steam)
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet run --no-restore --no-build -c Release --property WarningLevel=0 -- as-main steam app index -o $GITHUB_WORKSPACE/json -a 1086940

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Detect new and modified .json files
        id: detect-changes
        run: |
          git fetch origin
          git status
          git add json/*.json
          git status --short json/*.json > changed_files.txt
      
          echo "New files:" > report.txt
          grep '^??' changed_files.txt | awk '{print $2}' >> report.txt
          echo "" >> report.txt
          echo "Modified files:" >> report.txt
          grep '^ M' changed_files.txt | awk '{print $2}' >> report.txt
      
          cat report.txt
          

     
      
          
          
