name: Update Game Hashes

on:
  workflow_dispatch:

jobs:
  update-game-hashes:
    strategy:
      matrix:
        store:
          - steam 
        game:
          - StardewValley
          
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Clone the NexusMods.App repo
      - name: Clone NexusMods.App & Make Folders
        run: |
          mkdir output
          git clone https://github.com/Nexus-Mods/NexusMods.App
          cd NexusMods.App
          git submodule update --init --recursive

      - name: Build
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet build -c Release
          
      - name: Index ${{ matrix.game }} from ${{ matrix.store }}
        env:
          STEAM_USER: ${{ secrets.STEAM_USER }}
          STEAM_PASS: ${{ secrets.STEAM_PASS }}
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet run --no-restore --no-build -c Release --property WarningLevel=0 -- as-main ${{matrix.store}} app index -o $GITHUB_WORKSPACE/json -g ${{ matrix.game }}
