name: Update Game Hashes

on:
  workflow_dispatch:

jobs:
  update-game-hashes:
    strategy:
      matrix:
        cmd: 
          #- steam app index -a 413150 # Steam - Stardew Valley 
          #- steam app index -a 1091500 # Steam - Cyberpunk 2077
          - steam app index -a 2138330 # Steam - Cyberpunk 2077 - Phantom Liberty
          #- steam app index -a 1086940 # Steam = Baldurs Gate 3
        
  
    runs-on: self-hosted
    env:
        STEAM_USER: ${{ secrets.STEAM_USER }}
        STEAM_PASS: ${{ secrets.STEAM_PASS }}
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Clone the NexusMods.App repo
      - name: Clone NexusMods.App & Make Folders
        run: |
          mkdir output
          git clone https://github.com/Nexus-Mods/NexusMods.App
          cd NexusMods.App
          git submodule update --init --recursive

      - name: Build
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet build -c Release
          
      - name: Run Indexer ${{ matrix.cmd }}
        run: |
          cd NexusMods.App/src/NexusMods.App
          dotnet run --no-restore --no-build -c Release --property WarningLevel=0 -- as-main ${{ matrix.cmd }} -o $GITHUB_WORKSPACE/json 

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      
      - name: Detect new and modified .json files
        id: detect-changes
        run: |
          git fetch origin
          git status
          git add json/
          git status --short json/ > changed_files.txt
      
          echo "New files:" > report.txt
          grep '^??' changed_files.txt | awk '{print $2}' >> report.txt
          echo "" >> report.txt
          echo "Modified files:" >> report.txt
          grep '^ M' changed_files.txt | awk '{print $2}' >> report.txt
      
          cat report.txt
      
          if [ -s changed_files.txt ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Generate unique branch name
        if: steps.check-json.outputs.changed == 'true'
        id: branch-name
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          BRANCH="update-game-hashes-${TIMESTAMP}"
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.check-json.outputs.changed == 'true'
        run: |
          git checkout -b ${{ steps.branch-name.outputs.branch }}
          git add json/**/*.json json/*.json
          git commit -m "Update game hashes"
          git push origin ${{ steps.branch-name.outputs.branch }}

      - name: Create Pull Request
        if: steps.check-json.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch-name.outputs.branch }}
          title: "Update game hashes"
          body: |
            This PR updates the game hashes based on the latest index run.
          delete-branch: true

     
      
          
          
